---

- name: Prepare | install dependencies
  hosts: all
  become: true
  tasks:
    - name: install dependencies (RedHat based systems)
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == "RedHat"
    - name: install dependencies(Debian based systems)
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"
  vars:
    packages:
      - curl
      - python3-pip
      - docker-compose

- name: Prepare | install docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_service_state: started
    docker_restart_handler_state: stopped
    docker_service_enabled: false
